type RemigrarSearchRoot = {
  disk: string;
  basePath: string;
};

/** Gerado a partir do listing de /storage/app/user_files/empresas */
export const SICREDI_REMIGRAR_USER_FILES_ROOTS: RemigrarSearchRoot[] = [
  { disk: "user_files", basePath: "empresas/ag06ivotramontina/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/monte_belo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag03sus/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag07bomprincipio/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag07bp/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag09tupandi/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag10bento/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag11NovaR/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag12fava/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag16floresc/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag19Cpilar/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag1sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag1sureg-old/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag20np/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag26barao/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag27barmau/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag30CaBar/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag31Gari/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag34bento/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag37vera/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediserrana0167-ag39fc/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-9jul46/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-Capitao11/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-ItuCentro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-Itupeva25/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-PedraBela/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-ampere10/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-anchieta39/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-atatiba36/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-atibaia23/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-barracao12/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-bjesus13/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-bomjesus40/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-brag22/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-bragp33/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-cabreuva35/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-caja38/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-campolp31/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-capanema07/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-caroba05/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-guara17/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-itatiba20/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-itatibac34/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-itu24/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-jarinu30/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-jundiai21/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-lou28/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-mairipora32/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-morunga42/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-palma18/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-paulista29/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-perola03/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-pinhal41/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-piracaia44/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-pirapora43/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-planalto06/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-pranchita08/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-rangel26/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-realeza02/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-salgado14/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-santa04/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-santal19/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-santo09/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-saocedro16/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-sureg01/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-vinhedo27/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredifronteiras-vistapr15/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredialtosdaserracoop0268/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucarai-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag02arvorezinha/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag04tunas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag05novaalvorada/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag06ibirapuita/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag07itapuca/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag11fontouraxavier/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag12saojosedoherval/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredibotucaraiag14missoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag02/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag03/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag04/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag05/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag06/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag07/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag08/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag09/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag10/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag11/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag12/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag13/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag14/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag15/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag16/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag17/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag18/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidasculturascoop0361ag21/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagaucho-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag02manoelviana/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag03quarai/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag05rosariodosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag06saogabriel/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag11uruguaiana/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredidopampagauchoag13alegretecidadealta/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediespumosocoop0218/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredigrandepalmeiracoop0229/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediintegracaodosestadosrs/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-arroioGd/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-bage01/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-bageII/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-bageSede/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-candiota/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-coloniaNv/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-dompedrito/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-herval/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-hulhaNg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-jaguarao/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-pedraAlt/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-pedroOso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediliberdade-pinheiroMa/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag02crissiumalrural/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag03horizontinaurbana/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag04humaita/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag05boavista/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag06tiradentesdosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag07doutormauriciocardoso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag08saojosedoinhacora/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag09independencia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag10alegria/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag11inhacora/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag12novacandelaria/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag17tresdemaio/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag18horizontinarural/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag24esquinaaraujo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag25consolata/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag26vilacascata/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag27tresdemaioruahorizontina/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-ag28crissiumalurbana/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredinoroeste-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-agenciaon/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-altofeliz/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-anarech26/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-avbrasil52/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-canudos24/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centcanela34/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centgramado17/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centnovpetro98/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centro14/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centrofeliz09/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-centroSL23/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-cruzeiro28/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-desviorizzo40/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-doisirmaos19/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-emprserra97/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-estvelha33/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-feevale25/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-feitoria55/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-forqueta053/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-galopolis/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-gramado17/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-hortencio16/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-impe39/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-ivoti18/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-ivoti56/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-jpessoa57/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-lindolfoc42/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-lnova07/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-lombgran44/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-lourdes31/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-mreuter/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-novapetro13/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-ourobr38/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-pcafe005/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-piai35/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-pinhal06/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-piox20/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-portao21/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-prelucena08/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-rbranco30/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-rincao11/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-riobrancosl/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-santaL46/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-sanvitto45/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-saomiguel51/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-scharlau36/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-sfpaula41/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-SHerval02/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-spedro54/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-unisinos22/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-varzeagrande43/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-vcristina04/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-vintesetem12/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredipioneira-vreal10/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag02saomartinho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag03bomprogresso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag04camponovo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag05trespassos/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag06braga/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag07sedenova/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag08redentora/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag09tenenteportela/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag10vistagaucha/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag11derrubadas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag12esperancadosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag13miraguai/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag14barradoguarita/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag15saomigueldooeste/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag16iporadooeste/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag17mondai/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag18descanso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag19saojoaodooeste/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag20itapiranga/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag21trespassos-costaesilva/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag22jaboticaba/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag23novobarreiro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag24sagradafamilia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag25saojosedasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag26doisirmaosdasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag27lageadodobugre/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag28boavistadasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag29palmeiradasmissoespfeagro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag30saopedrodasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag31palmeiradasmissoesempresarial/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag32tunapolis/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag33jardimoeste/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag34bocaiuva/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag35olhosdagua/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag36curvelo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag37jfilho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag38shelena/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-ag39felix/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediraizes-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducao-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag02/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag03/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag04/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag05/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag07/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag08/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag09/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag10/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag11/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag12/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag13/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag14/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag15/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag16/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag17/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag18/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag19/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag22/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag23/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag24/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag25/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag26/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag28/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediregiaodaproducaocoop0258-ag31/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredirotadasterrascoop0244/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag01sede/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag02saopedro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag55saude/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag5614junho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag57Sangelo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag58sulina/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag59felix/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag60digital/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag70itape/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag71mara/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag72neves/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag73gilberto/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag74castelo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag75alegre/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag76guaçui/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag77acisci/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag78apiaca/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag79mimoso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag82kennedy/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag86castelo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag90atend/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniao0307-ag92vargem/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag02saopedrodobutia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag03salvadordasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag04guaranidasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag05saopaulodasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag06cerrolargo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag07roquegonzales/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag08portoxavier/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag12santoangelo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag13saoborja/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag14saoluizgonzaga/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag15santarosa-centro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag16dezesseisdenovembro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag17candidogodoi/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag18campinadasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag19santocristo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag20tucunduva/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag21saomigueldasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag22tuparendi/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag24girua/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag25vitoriadasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag26caibate/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag27novomachado/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag28entre-ijuis/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag29catuipe/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag30santoantoniodasmissoes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag31saonicolau/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag32bairrocruzeiro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag34bossoroca/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag35portomaua/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag36senadorsalgadofilho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag37pracadaindependecia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag38alecrim/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag39portolucena/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag40bairropippi/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag43getuliovargas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag44senadorpinheiromachado(slg)/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag45eugeniodecastro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag46vilacatarina/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag47setedesetembro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag48matoqueimado/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag49ubiretama/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag50bairrodopasso/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag51portovercruz/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag52guarulhos/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag53rolador/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag54pirapo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag70cachoeirodoitapemerim/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-ag71marataizes/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniaocooperativa0307-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag02gaurama/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag03aratiba/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag04viadutos/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag05campinasdosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag06baraodecotegipe/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag07saovalentim/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag08ervalgrande/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag09itatibadosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag10marcelinoramos/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag11maximiliano/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag12paulobento/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag13marianomoro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag14severianodealmeida/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag15benjamiconstantdosul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag15benjamim/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag16aurea/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag17erechimcentro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag18tresarroios/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag19faxinalzinho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag20erechimsantodalbosco/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag21entrerios/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag22barradorioazul/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag24erechimtresvendas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag25centenario/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag26pontepreta/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag27joacaba/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag28erechimpracajaymelago/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag29seara/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag30ouro/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag31bairroatlantico/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag33concordia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag34piratuba/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag35catanduvas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag36ita/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag39ipira/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag40concordia/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag41cruzaltense/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag42altobelavista/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag43luzerna/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag44peritiba/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag45pj/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag46hervaldoeste/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag47ipumirim/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag48alfenas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag49andradas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag50irani/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag51jabora/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag52machado/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag53jacutinga/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag54concordiaempresarial/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag55pocosdecaldas/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag56ourofino/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag57ervalvelho/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag58arabuta/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag59arvoredo/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-ag60paraguacu/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediuniestados-sureg/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicrediunimedmissoes0063/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "user_files", basePath: "empresas/sicredividaesaude0055/digitalizacao/ASSOCIADOS ATIVOS" },
];

export const SICREDI_REMIGRAR_BACKUP_ROOTS: RemigrarSearchRoot[] = [
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA" },
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA/digitalizacao" },
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA/migracao" },
  { disk: "backup", basePath: "MUNICIPIO DE RONDA ALTA/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento/migracao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag10bento/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar/migracao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag30CaBar/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "serrana-27barmau" },
  { disk: "backup", basePath: "serrana-27barmau/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "serrana-27barmau/digitalizacao" },
  { disk: "backup", basePath: "serrana-27barmau/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "serrana-27barmau/migracao" },
  { disk: "backup", basePath: "serrana-27barmau/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc/migracao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag16floresc/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc/migracao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag39fc/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar/digitalizacao_old/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar/migracao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag19Cpilar/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana/AG 07 BOM PRINCIPIO" },
  { disk: "backup", basePath: "sicrediserrana/AG 12 FAGUNDES VARELA" },
  { disk: "backup", basePath: "sicrediserrana/AG 34 AGRO BENTO" },
  { disk: "backup", basePath: "sicrediserrana/AG 18 FLORES DA CUNHA - SAO GOTARDO" },
  { disk: "backup", basePath: "sicrediserrana/AG 16 FLORES DA CUNHA" },
  { disk: "backup", basePath: "sicrediserrana/AG 26 BARÃO" },
  { disk: "backup", basePath: "sicrediserrana/AG 20 NOVA PADUA" },
  { disk: "backup", basePath: "sicrediserrana0167-ag07bomprincipio/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag07bomprincipio/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag12fava/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag12fava/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag20np/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag20np/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag26barao/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag26barao/digitalizacao" },
  { disk: "backup", basePath: "sicrediserrana0167-ag37vera/digitalizacao/ASSOCIADOS ATIVOS" },
  { disk: "backup", basePath: "sicrediserrana0167-ag37vera/digitalizacao" },
];
